# .bash_profile
echo "fall .bash_profile 0"
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

echo "fall .bash_profile 1"
export PATH
